# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [ ]:

import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix



## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [2]:

import numpy as np
# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


(True,
 array([[ 0.70710678+0.j        ,  0.70710678+0.j        ],
        [ 0.        +0.70710678j, -0.        -0.70710678j]]))

# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [3]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v


array([ -7.+16.j,  -9.+22.j,  -9.+38.j, -11.+52.j])


## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [4]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


array([[-11. +28.j, -13. +34.j, -13. +66.j, -15. +80.j],
       [-15. +40.j, -17. +46.j, -17. +94.j, -19.+108.j],
       [-15.+104.j, -17.+126.j, -17.+142.j, -19.+172.j],
       [-19.+148.j, -21.+170.j, -21.+202.j, -23.+232.j]])

# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)



## /

## /

## /

## Solucion de ejercicios

### Ejercicio 1 Complex Hermitian Matrices

Considere la siguiente matriz:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verique si $ H $ es una matriz Hermitiana.
- si lo llega a ser, encuentra los valores propios.

In [5]:
import numpy as np

# Define una matriz hermitiana compleja.
hermitian_matrix = np.array([[3+0j, 2+1j], 
                             [2-1j, 1+0j]])

eigenvalues, eigenvectors = np.linalg.eig(hermitian_matrix)

# comprobar si la matriz es hermitiana
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)
def hermitian(matriz,eshermitiana,valorespropios):
    if eshermitiana == True:
        return (f"la matriz si es hermitiana y sus valores propios son:{valorespropios}")
    else:
        return("la matriz no es hermitiana")
    
print(hermitian(hermitian_matrix,is_hermitian,eigenvalues))



la matriz si es hermitiana y sus valores propios son:[ 4.44948974-6.70989255e-17j -0.44948974+1.15877743e-17j]


## Ejercicio 2: Complex Unitary Matrices

Considere la matriz:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verique si $ U $ es una matriz unitaria.
- pruebe la operacion $ UU^\dagger $ para confirmar que es unitario donde $ U^\dagger $ denota el conjugado transpuesto de $ U $.

In [20]:
# Define la matriz compleja 
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)*1j], [1/np.sqrt(2)*1j, 1/np.sqrt(2)]])
#codigo para saber si es unitaria
matriz_u = unitary_matrix.conj().T

mtztotal =np.dot(unitary_matrix,matriz_u)

is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

print(f"La matriz adjunta U† es:\n{matriz_u}\n")
print(f"El resultado de UU† es:\n{mtztotal}\n")
print(f"¿Es U una matriz unitaria? {is_unitary}")

La matriz adjunta U† es:
[[0.70710678-0.j         0.        -0.70710678j]
 [0.        -0.70710678j 0.70710678-0.j        ]]

El resultado de UU† es:
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]

¿Es U una matriz unitaria? True


## Ejercicio 3: producto tensor para vectores complejos

utilizando el vector complejo:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calcular el producto tensor $ \mathbf{v} \otimes \mathbf{w} $.

In [59]:

import numpy as np

# Definimos los dos vectores
v1 = np.array([1+1j, 1-2j])
v2 = np.array([2-1j, 3+0j])

# Calculamos el producto tensor
tensor_product_v = np.kron(v1, v2)
print("el resultado del producto tensor para vectores complejos")
print(tensor_product_v)

el resultado del producto tensor para vectores complejos
[3.+1.j 3.+3.j 0.-5.j 3.-6.j]


## Ejercicio 4: producto tensor de matrices complejas

dadas las siguientes matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calcula el produrcto tensor $ M_1 \otimes M_2 $.

In [60]:
# Definimos las dos matrices complejas 
M1 = np.array([[0,1],[1,0]])
M2 = np.array([[1j,0],[0,-1j]])

# Calculamos el producto tensor
tensor_product_m = np.kron(M1, M2)

print("el producto tensor de las matrices es")
print(tensor_product_m)


el producto tensor de las matrices es
[[0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.-0.j]]


## Ejercicio 5: modelacion de la computacion cuantica con matrices y vectores

usando las matrices y los vectores, implementalas en el modelo de interferometro de Mach/Zehnder .

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

In [68]:
import numpy as np

quetzero = np.array([[1],[0]])
H = np.array([[1, 1], [1, -1]]) / np.sqrt(2) 
X = np.array([[0, 1], [1, 0]])  
totalmult1 = np.dot(H,quetzero)
totalmult2 = np.dot(X,totalmult1)
totalmult3 = np.dot(H,totalmult2)

print(f"El resultado de aplicar los calculos referentes para la imagen es ")
print(f"{totalmult3}")
print("que siendo mas preciso seria quet(O) lo cual es una matriz de la forma ")

El resultado de aplicar los calculos referentes para la imagen es 
[[1.00000000e+00]
 [2.23711432e-17]]
que siendo mas preciso seria quet(O) lo cual es una matriz de la forma [1,0] 



$$ \mathbf{V} = \begin{bmatrix} 1 \\ 0 \end{bmatrix} $$

## Ejercicio 6: componer sistemas cuanticos

usando matrices y vectores, implementar un modelo de un circuito en seguimiento.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

esta es la matriz $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)


In [77]:
import numpy as np
### Definimos el vector quetzero
quetzero = np.array([[1],[0]])
### Definimos el vector quetuno
quetuno = np.array([[0],[1]])
### Definimos la matriz H 
H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
### Definimos la matriz identidad cuadrada 2x2
inden = np.array([[1, 0], [0, 1]])
### Definimos la matriz Uf
Uf = np.array([[0,1,0,0], [1,0,0,0],[0,0,1,0], [0,0,0,1]])
quetfi1 = np.kron(quetzero,quetuno)
quetfi2 = np.dot((np.kron(H,H)),quetfi1)
quetfi3 = np.dot(Uf,quetfi2)
quetfi4 = np.dot((np.kron(H,inden)),quetfi3)
print("el resultado del modelo es:")
print(quetfi4)



el resultado del modelo es:
[[ 0.        ]
 [ 0.        ]
 [-0.70710678]
 [ 0.70710678]]
